# Generated by Django 5.0 on 2025-10-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
