# Generated by Django 5.0 on 2025-09-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_category_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='featured_order',
            field=models.PositiveIntegerField(default=0, help_text='Order on homepage (low first)'),
        ),
    ]
